create table "public"."restaurante_reservas" (
  "id"             bigint                   generated by default as identity not null,
  "created_at"     timestamp with time zone not null default now(),
  "restaurante_id" bigint,
  "nome_cliente"   text,
  "email_cliente"  text,
  "telefone"       text,
  "data_reserva"   date,
  "hora_reserva"   time without time zone,
  "numero_pessoas" bigint,
  "observacoes"    text,
  "user_id"        uuid,
  constraint "fk_restaurante_reservas_user_id" foreign key (user_id) references auth.users(id) on delete cascade,
  constraint "restaurante_reservas_pkey" primary key (id),
  constraint "restaurante_reservas_restaurante_id_fkey" foreign key (restaurante_id) references public.restaurantes(id) on delete restrict
);

alter table "public"."restaurante_reservas"
  enable row level security;

create index idx_restaurante_reservas_email on public.restaurante_reservas using btree (email_cliente);

create index idx_restaurante_reservas_user_id on public.restaurante_reservas using btree (user_id);

create policy "Cancelar sua reserva" on "public"."restaurante_reservas"
  for delete
  to PUBLIC
  using ((auth.uid() = user_id));

create policy "Criar reserva com user_id" on "public"."restaurante_reservas"
  for insert
  to PUBLIC
  with check (((auth.uid() = user_id) OR (user_id IS NULL)));

create policy "Editar sua reserva" on "public"."restaurante_reservas"
  for update
  to PUBLIC
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Permitir criacao publica de reservas" on "public"."restaurante_reservas"
  for insert
  to "anon", "authenticated"
  with check (true);

create policy "Utilizador vê suas reservas" on "public"."restaurante_reservas"
  for select
  to PUBLIC
  using (((auth.uid() = user_id) or (auth.uid() is null)));

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."restaurante_reservas" to "anon", "authenticated", "postgres", "service_role";
