-- REMOVIDO 13/09/2026 — este ficheiro usava
-- `EXCEPTION WHEN others THEN RAISE NOTICE 'PASS'`, que dava "PASS" tanto
-- se a policy bloqueasse o INSERT como se a função por trás rebentasse
-- por outro motivo qualquer. Foi este padrão que escondeu o bug do
-- e_menor_agora() (ver docs/sessions/SESSAO-20260912.md).
--
-- Sem acesso a terminal nesta sessão para apagar o ficheiro fisicamente,
-- por isso o conteúdo foi esvaziado aqui para deixar de dar falsa
-- cobertura. Podes apagar o ficheiro com:
--   rm supabase/tests/security/rls-policies-block.test.sql
--
-- Um teste real teria de distinguir "bloqueado pela policy" (código
-- Postgres 42501) de qualquer outra exceção, e falhar nesse segundo caso.
