-- Mundo dos Patudos — Fase 1: publicações, fotografias e denúncias.
-- Aplicação manual futura. Não altera marketplaces nem o módulo social.
begin;

create or replace function public.pet_is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.is_admin = true and p.deleted_at is null
  );
$$;
revoke all on function public.pet_is_admin() from public;
grant execute on function public.pet_is_admin() to anon, authenticated, service_role;

create table public.pet_posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  submission_key uuid not null,
  kind text not null check (kind in ('adoption', 'lost', 'found', 'help')),
  status text not null default 'draft' check (status in ('draft', 'published', 'resolved', 'archived')),
  title varchar(120) not null check (char_length(btrim(title)) between 5 and 120),
  description text not null check (char_length(btrim(description)) between 30 and 5000),
  pet_name varchar(80),
  species text not null check (species in ('dog', 'cat', 'bird', 'other')),
  sex text not null default 'unknown' check (sex in ('male', 'female', 'unknown')),
  size text check (size is null or size in ('small', 'medium', 'large')),
  age_label varchar(60),
  breed varchar(100),
  color varchar(100),
  freguesia_id bigint not null references public.freguesias(id),
  location_detail varchar(180),
  event_at timestamptz,
  is_urgent boolean not null default false,
  published_at timestamptz,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (author_id, submission_key),
  check (pet_name is null or char_length(btrim(pet_name)) between 1 and 80),
  check (age_label is null or char_length(btrim(age_label)) between 1 and 60),
  check (breed is null or char_length(btrim(breed)) between 1 and 100),
  check (color is null or char_length(btrim(color)) between 1 and 100),
  check (location_detail is null or char_length(btrim(location_detail)) between 1 and 180),
  check (kind in ('lost', 'found') or event_at is null),
  check (not is_urgent or kind = 'help')
);
alter table public.pet_posts enable row level security;
create index pet_posts_feed on public.pet_posts(status, created_at desc);
create index pet_posts_location on public.pet_posts(freguesia_id, status, created_at desc);
create index pet_posts_kind on public.pet_posts(kind, status, created_at desc);
create index pet_posts_author on public.pet_posts(author_id, created_at desc);
create trigger pet_posts_updated_at before update on public.pet_posts
for each row execute function public.handle_updated_at();

create or replace function public.pet_post_guard()
returns trigger language plpgsql set search_path = '' as $$
begin
  if TG_OP = 'UPDATE' and auth.role() = 'authenticated' and not public.pet_is_admin() then
    if new.id is distinct from old.id or new.author_id is distinct from old.author_id
      or new.submission_key is distinct from old.submission_key
      or new.created_at is distinct from old.created_at then
      raise exception 'Campos imutáveis' using errcode = '42501';
    end if;
  end if;
  if new.status = 'published' and old.status is distinct from 'published' then
    new.published_at := statement_timestamp();
  end if;
  if new.status = 'resolved' and old.status is distinct from 'resolved' then
    new.resolved_at := statement_timestamp();
  elsif new.status <> 'resolved' then
    new.resolved_at := null;
  end if;
  return new;
end;
$$;
revoke all on function public.pet_post_guard() from public;
create trigger pet_post_guard before update on public.pet_posts
for each row execute function public.pet_post_guard();

create policy "pets public feed" on public.pet_posts for select to public
using (status in ('published', 'resolved') or author_id = auth.uid() or public.pet_is_admin());
create policy "pets authenticated insert" on public.pet_posts for insert to authenticated
with check (author_id = auth.uid() and status in ('draft', 'published'));
create policy "pets owner update" on public.pet_posts for update to authenticated
using (author_id = auth.uid() or public.pet_is_admin())
with check (author_id = auth.uid() or public.pet_is_admin());
create policy "pets owner delete draft" on public.pet_posts for delete to authenticated
using ((author_id = auth.uid() and status = 'draft') or public.pet_is_admin());
grant select on public.pet_posts to anon, authenticated;
grant insert, update, delete on public.pet_posts to authenticated;
grant all on public.pet_posts to service_role;

create table public.pet_photos (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.pet_posts(id) on delete cascade,
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  storage_path text not null unique,
  sort_order smallint not null default 0 check (sort_order between 0 and 2),
  mime_type text not null check (mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  size_bytes integer not null check (size_bytes between 1 and 4194304),
  created_at timestamptz not null default now(),
  unique (post_id, sort_order)
);
alter table public.pet_photos enable row level security;
create index pet_photos_post on public.pet_photos(post_id, sort_order);
create policy "pets photos follow post visibility" on public.pet_photos for select to public
using (exists (select 1 from public.pet_posts p where p.id = post_id));
create policy "pets owner inserts photos" on public.pet_photos for insert to authenticated
with check (uploader_id = auth.uid() and exists (
  select 1 from public.pet_posts p where p.id = post_id and p.author_id = auth.uid()
));
create policy "pets owner deletes photos" on public.pet_photos for delete to authenticated
using (uploader_id = auth.uid() or public.pet_is_admin());
grant select on public.pet_photos to anon, authenticated;
grant insert, delete on public.pet_photos to authenticated;
grant all on public.pet_photos to service_role;

create table public.pet_reports (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.pet_posts(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('incorrect', 'unsafe', 'fraud', 'duplicate', 'other')),
  details varchar(1000),
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id),
  unique (post_id, reporter_id),
  check (details is null or char_length(btrim(details)) between 3 and 1000)
);
alter table public.pet_reports enable row level security;
create index pet_reports_pending on public.pet_reports(created_at) where status = 'pending';
create policy "pets reports own or admin read" on public.pet_reports for select to authenticated
using (reporter_id = auth.uid() or public.pet_is_admin());
create policy "pets reports authenticated insert" on public.pet_reports for insert to authenticated
with check (reporter_id = auth.uid() and status = 'pending');
create policy "pets reports admin update" on public.pet_reports for update to authenticated
using (public.pet_is_admin()) with check (public.pet_is_admin());
grant select, insert on public.pet_reports to authenticated;
grant update on public.pet_reports to authenticated;
grant all on public.pet_reports to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('pet-media', 'pet-media', true, 4194304,
  array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.pet_media_can_write(p_name text)
returns boolean language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null
    and p_name ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}/[0-9a-f-]{36}\.(jpg|jpeg|png|webp)$'
    and split_part(p_name, '/', 1) = auth.uid()::text
    and exists (
      select 1 from public.pet_posts p
      where p.id::text = split_part(p_name, '/', 2) and p.author_id = auth.uid()
    );
$$;
revoke all on function public.pet_media_can_write(text) from public;
grant execute on function public.pet_media_can_write(text) to authenticated, service_role;

create policy "pet media public read" on storage.objects for select to public
using (bucket_id = 'pet-media');
create policy "pet media owner insert" on storage.objects for insert to authenticated
with check (bucket_id = 'pet-media' and public.pet_media_can_write(name));
create policy "pet media owner delete" on storage.objects for delete to authenticated
using (bucket_id = 'pet-media' and public.pet_media_can_write(name));
-- Policies restritivas impedem que uma policy permissiva de outro módulo abra
-- acidentalmente escritas neste bucket. São neutras para todos os outros buckets.
create policy "pet media insert guard" on storage.objects as restrictive for insert to public
with check (bucket_id <> 'pet-media' or
  (auth.role() = 'authenticated' and public.pet_media_can_write(name)));
create policy "pet media update guard" on storage.objects as restrictive for update to public
using (bucket_id <> 'pet-media') with check (bucket_id <> 'pet-media');
create policy "pet media delete guard" on storage.objects as restrictive for delete to public
using (bucket_id <> 'pet-media' or
  (auth.role() = 'authenticated' and public.pet_media_can_write(name)));

commit;
